### ISSUE TITLE
Frnkz404

### ISSUE THREAD

**Issue by Frnkz404** [AbilSeno/MDSpammers#2]
Spam Ny Ga Bekerja, Cuma Sampe 9 Baris

**Comment by cimol07** [comment]
wah di bales, jadi gimana bang, ak slalu nunggu update dari abang yg lain
kalah sama SC abang, bang berjuang ya fix SC nya, aku selalu nunggu SC dri
abang. sehat selalu bang. makasi dah reply

Pada tanggal Rab, 25 Nov 2020 17.01, 74769995ff5a786bed94a02d1030a9b7 <
notifications@github.com> menulis:

**Comment by Frnkz404** [comment]
Maksudny bang?

**Comment by cimol07** [comment]
jadi gimana bang biar fix lagi SC nya selalu connection error

Pada tanggal Rab, 25 Nov 2020 17.14, 74769995ff5a786bed94a02d1030a9b7 <
notifications@github.com> menulis:

**Comment by Frnkz404** [comment]
Sorry bang, ane bukan authornya, ane cuma mau nanya ke authornya aj wkwk

**Comment by cimol07** [comment]
lah😂😂😂😂 authornya sapa emang bang

Pada tanggal Rab, 25 Nov 2020 17.20, 74769995ff5a786bed94a02d1030a9b7 <
notifications@github.com> menulis:

**Comment by abilify1** [comment]
udah di fix
Ketik 
```
cd MDSpammers
git pull
```

**Comment by cimol07** [comment]
makasi bgt bang, btw sapa ya autornya kalo bole tau sih bang

Pada tanggal Rab, 25 Nov 2020 17.45, AbilSeno <notifications@github.com>
menulis:

**Comment by cimol07** [comment]
Pada tanggal Rab, 25 Nov 2020 17.46, Cimol <ainol.yaqin222@gmail.com>
menulis:

**Comment by Frnkz404** [comment]
> udah di fix
> Ketik
> 
> ```
> cd MDSpammers
> git pull
> ```

Mantep Nih, Cuman Ane Fix Sendiri🤦
