### ISSUE TITLE
BANG SCRIPTNYA ADA YANG ERROR

### ISSUE THREAD

**Issue by Capixs** [AbilSeno/MDSpammers#7]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    ses("28","sms","temanprima")\n #else:\n  #gagal("28","sms","temanprima")\ndef maripinjam():\n hd={\n'Host':'api.guntur.top',\n'Connection':'Keep-Alive',\n'Accept-Encoding':'gzip',\n'User-Agent':'okhttp/3.8.0',\n'pm-osType':'3',\n'pm-osversion':'28',\n'pm-osdevice':'bce68810-4f8a-4675-9452-e0d8565c9a50',\n'pm-clientId':'-1',\n'Accept-Language':'in-ID',\n'Connection':'close',\n'pm-appversion':'V1.2.4',\n'vest':'521',\n'packageName':'com.inacashkangaroo.app',\n'phoneModel':'vivo 1902'\n }\n ijo=requests.get("https://api.guntur.top/a0jm6akw/hvfgpv71/wzq12mqh/"+nom+"/2",headers=hd).text\n if json.loads(ijo)["success"] == True:\n  sukses("29","sms","maripinjam")\n else:\n  gagal("29","sms","maripinjam")\ndef sobatbangun():\n# h = json.loads(requests.post("https://www.sobatbangun.com/otp-validation?p_p_id=SB_Registration_Otp_Portlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=sendVerificationCode&p_p_cacheability=cacheLevelPage&_SB_Registration_Otp_Portlet_mobilePhoneNo=0%s"%nom,headers={'user-agent':'Mozilla/5.0 (Linux; Android 9; vivo 1902) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.136 Mobile Safari/537.36'}).text)\n #if h["status"] == 'success':\n  sukses("30","wa","sobatbangun")\n #else:\n  #gagal("30","wa","sobatbangun")\n\n\nif __name__ == '__main__':\n try:\n  os.system("clear")\n  logo()\n  input()\n except (KeyboardInterrupt,EOFError): print "%s[%s!%s] %sExit"%(pu,me,pu,pu)\n except requests.exceptions.ConnectionError: exit("%s[%s!%s] %sConnection Error..."%(pu,me,pu,me))\n"""
  File "<string>", line 302, in <module>
  File "<string>", line 43, in input
File "<string>", line 21, in main
  File "<string>", line 111, in bakmikeraton
  File "/data/data/com.termux/files/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by AbilSeno** [comment]
``
